version: '3'  # version of compose format 

services:
  client:
    build: ./client  # path is relative to docker-compose.yml localtion
    volumes:
      - ./client:/usr/src/app # mount point
    ports:
      - 5001:80  # host:container
    depends_on:
      - server
    networks:
      - my_network      

  server:
    build: ./server  # path is relative to docker-compose.yml localtion
    volumes:
      - ./server:/usr/src/app # mount point
    ports:
      - 5000:80  # host:container  
    networks:
      - my_network
 
networks: 
  my_network:
    driver : bridge      